[package]
name = "lapdev-kube"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
base64.workspace = true
anyhow.workspace = true
kube = { version = "0.98.0", features = [] }
k8s-openapi = { version = "0.24.0", features = ["latest"] }
